### ISSUE TITLE
Latest Master Fails on Syntax Error

### ISSUE THREAD

**Issue by lxcodes** [jmacul2/sentry-cfml#2]
```
/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:808: RuntimeWarning: DateTimeField received a naive datetime (2013-02-24 19:39:00) while time zone support is active.
  RuntimeWarning)
Internal Server Error: /nerdery/demoinq/group/324/
Traceback (most recent call last):
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/web/decorators.py", line 140, in wrapped
    return prv_func(request, team_slug=team_slug, project_id=project_id, group=group, *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/web/decorators.py", line 150, in wrapped
    return func(request, *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/web/decorators.py", line 110, in _wrapped
    return func(request, *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/web/frontend/groups.py", line 360, in group
    return render_with_group_context(group, template, context, request, event=event)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/web/frontend/groups.py", line 195, in render_with_group_context
    return render_to_response(template, context, request)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/web/helpers.py", line 157, in render_to_response
    response = HttpResponse(render_to_string(template, context, request))
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/web/helpers.py", line 153, in render_to_string
    return loader.render_to_string(template, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/loader.py", line 171, in render_to_string
    return t.render(Context(dictionary))
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 474, in render
    self.extra_context.iteritems()])
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 599, in resolve
    new_obj = func(obj, *arg_vals)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/templatetags/sentry_helpers.py", line 345, in get_rendered_interfaces
    for interface in event.interfaces.itervalues():
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/cache.py", line 96, in __get__
    value = self.func(obj)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/models.py", line 685, in interfaces
    cls = import_string(key)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/imports.py", line 38, in import_string
    result = _cache[path]
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/imports.py", line 15, in __missing__
    module = __import__(module_name, {}, {}, [class_name], -1)
  File "/var/www/sentry/src/sentry-cfml/sentry_cfml/interfaces.py", line 71
    })
     ^
SyntaxError: invalid syntax
```

Apologies if I did something wrong -- but just noticed this after an upgrade of Sentry. Let me know if I can help in any way.

**Comment by jmacul2** [comment]
sorry about that.  fixed.

**Comment by lxcodes** [comment]
@jmacul2 Thanks for the amazingly quick fix. Made my Tuesday morning.
