### ISSUE TITLE
_ Not Defined

### ISSUE THREAD

**Issue by lxcodes** [jmacul2/sentry-cfml#4]
I'm also getting the error below --

```
Error processing 'post_process' on 'MailProcessor': global name '_' is not defined
Traceback (most recent call last):
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/safe.py", line 16, in safe_execute
    result = func(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/plugins/bases/notify.py", line 189, in post_process
    self.notify_users(group, event)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/plugins/sentry_mail/models.py", line 148, in notify_users
    interface_list.append((interface.get_title(), body))
  File "/var/www/sentry/src/sentry-cfml/sentry_cfml/interfaces.py", line 84, in get_title
    return _('CFML Request')
NameError: global name '_' is not defined
```

I'm not sure if this is as easy a fix as the last, but I believe this is the i18n method call? Not sure if it's missing from sentry now or the like. If you point me in the right direction, I'll provide a pull request with a fix.

**Comment by jmacul2** [comment]
Fixed.  Thanks.

**Comment by lxcodes** [comment]
@jmacul2 Again -- great response time. Thanks for the project and work =]
